services:
  photoview:
    image: viktorstrate/photoview:2
    hostname: photos
    container_name: photoview
    restart: always
    env_file:
      - ../.env
      - .env
    stop_grace_period: 10s
    networks:
      - proxy
      - mariadb-internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.photoview.entryPoints=https
      - traefik.http.routers.photoview.tls=true
      - traefik.http.routers.photoview.middlewares=default@file
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    user: ${PUID}:${PGID}
    depends_on:
      mariadb:
        condition: service_healthy
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        limits:
          pids: 300
          cpus: "2"
          memory: 2G
    volumes:
      - /etc/localtime:/etc/localtime:ro # use local time from host
      - /etc/timezone:/etc/timezone:ro # use timezone from host
      - /home/storage/nextcloud/glandix/files/Porn:/photos:ro
      - ${HOST_PHOTOVIEW_LOCATION}/sqlite:/home/photoview/sqlite
      - ${HOST_PHOTOVIEW_LOCATION}/storage:/home/photoview/media-cache
