services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    env_file:
      - ../.env
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.scrutiny.entrypoints=https
      - traefik.http.routers.scrutiny.tls=true
      - traefik.http.routers.scrutiny.middlewares=default@file
    tmpfs:
      - /tmp:rw,noexec,nosuid,uid=${PUID},gid=${PGID}
    volumes:
      - ./config:/opt/scrutiny/config
      - ./influxdb2:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/nvme0
    healthcheck:
      test: ps | grep scrutiny
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          pids: 500
          memory: 500M
    security_opt:
      - no-new-privileges=true
    restart: always
