services:
  proxy:
    image: traefik:v3.1
    container_name: proxy
    env_file:
      - ../.env
    restart: always
    networks:
      - proxy
      - influxdb
      - cloud
      - zigbee
    command: --providers.docker
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/config.d:/config.d:ro
      - ./logs:/logs
      - /home/storage/certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: "1"
          pids: 500
          memory: 3G
    security_opt:
      - no-new-privileges=true
    labels:
      - traefik.enable=true
      # https
      - traefik.http.routers.traefik.tls=true
      - traefik.docker.network=proxy
      - traefik.http.routers.traefik.entrypoints=https
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=default@file
