services:
  #
  # MARIADB
  #
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    env_file:
      - .env
      - ../.env
    networks:
      - mariadb-internal
    expose:
      - 3306
    user: ${PUID}:${PGID}
    volumes:
      - ./config:/etc/mysql/conf.d
      - ./mysqld:/var/run/mysqld
      - ./data:/var/lib/mysql
    restart: always
    healthcheck:
      test: [CMD, mariadb-admin, ping, -h, localhost, -u, healthcheck, "-p ${MARIADB_HEALTHCHECK_PASS}"]
      interval: 5s
      timeout: 20s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "4"
          pids: 500
          memory: 1G
    security_opt:
      - no-new-privileges=true

  #
  # PHPMYADMIN
  #
  phpmyadmin:
    container_name: phpmyadmin
    env_file:
      - ../.env
      - .env
    networks:
      - proxy
      - mariadb-internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.phpmyadmin.rule=Host(`mariadb.lloydnet.org`)
      - traefik.http.routers.phpmyadmin.entryPoints=https
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.routers.phpmyadmin.middlewares=default@file
    deploy:
      resources:
        limits:
          cpus: "1"
          pids: 50
          memory: 1G
    expose:
      - "80"
    restart: always
    healthcheck:
      test: curl -f http://localhost:80 -s
      interval: 30s
      timeout: 10s
      retries: 5
    security_opt:
      - no-new-privileges=true
    image: phpmyadmin:latest
    depends_on:
      - mariadb
