services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    env_file:
      - ../.env
      - .env
    networks:
      - proxy
    expose:
      - 8096
    ports:
      - 7359:7359/udp
    volumes:
      - ./config:/config
      - /home/storage/media:/media
      - /home/storage/certs:/certs:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.rule=Host(`media.lloydnet.org`) || Host(`jellyfin.lloydnet.org`)
      - traefik.http.routers.jellyfin.entryPoints=https
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.middlewares=default@file
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    group_add:
      - 110
      - 44
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/kfd:/dev/kfd
    restart: always
    healthcheck:
      test: curl -i http://localhost:8096/health -s
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "8"
          pids: 999
          memory: 8G
    security_opt:
      - no-new-privileges=true
