services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - ../.env
      - .env
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
    restart: always
    user: ${PUID}:${PGID}
    networks:
      - mongodb
    ports:
      - 127.0.0.1:27017:27017
      - 192.168.22.11:27017:27017
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ps ax | grep mongod
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "6"
          pids: 500
          memory: 1G
    security_opt:
      - no-new-privileges=true
